version: '2.4'

networks:
  server1:
  server2:
  server3:
  common:


services:
  supervisor_1: &supervisor
    extends:
      file: docker-compose-common-components.yml
      service: python
    command: supervisor
    depends_on:
      - postgres
      - redis
    networks:
      common:
      server1:
        aliases: 
          - supervisor
    volumes:
      - ./supervisor_data:/data
  backend_1: &backend
    hostname: api
    extends:
      file: docker-compose-common-components.yml
      service: python
    command: web
    depends_on:
        - postgres
        - redis
    networks:
      server1:
        aliases:
          - backend
      common:
  frontend_1: &frontend
    image: maresh/hll_rcon_frontend:latest
    ports:
      - ${RCONWEB_PORT}:80
      - ${RCONWEB_PORT_HTTPS}:443
      - ${PUBLIC_STATS_PORT}:81
      - ${PUBLIC_STATS_PORT_HTTPS}:444
    restart: always
    environment:
      RCONWEB_EXTERNAL_ADDRESS: ${RCONWEB_EXTERNAL_ADDRESS}
      HLL_HOST: ${HLL_HOST}
    volumes:
      - ./static:/static/
      - ./certs:/certs/
    depends_on:
      - backend_1
    networks:
      - server1
      - common
  redis:
    image: maresh/hll_redis:latest
    restart: always
    volumes:
      - ./redis_data:/data
    networks:
      - common
  postgres:
    image: postgres:12
    restart: always
    environment:
      # If a password is not defined this container will fail to create
      POSTGRES_PASSWORD: ${HLL_DB_PASSWORD}
      POSTGRES_USER: rcon
      POSTGRES_DB: rcon
      PGDATA: /data
    volumes:
      - ./db_data:/data
    networks:
      - common

