######################################################################################
######################################################################################
######################################################################################
######################################################################################
######################################################################################
# DO NOT change or delete this file
# Instead, to define your own config, copy it and rename it: "config.yml"
# Your own config will override the defaults
######################################################################################
######################################################################################
######################################################################################
######################################################################################

# Multi server related config, you can safe ignore those if you only have 1 server
MULTI_SERVERS:
  # This option when turned on will forward your temp ban to all your servers
  # When it is off the temp ban is only applied on the serveur where the command was received
  broadcast_temp_bans: yes
  # This option when turn on will forward the unban to all your servers
  # When is off unbanning a player will only apply on the serveur where the command was received
  broadcast_unbans: yes

# Config related to bans
BANS:
  # By setting this to yes, if you unban a player (temp or perma) it will also remove his blacklist (if any)
  unban_does_unblacklist: yes
  # Same as above but the other way around, remove a player from the blacklist will unban him
  unblacklist_does_unban: yes

# You can test your regex there: https://regex101.com/ set it to "Python"
NAME_KICKS: 
  regexps: []
  reason: "Your nickname is invalid"
  # If left unset, the webhook default to your audit log webhook
  discord_webhook_url: ""
  whitelist_flags: 
    - ✅

BAN_TK_ON_CONNECT:
  enabled: no
  message: "Your first action on the server was a TEAM KILL you were banned as a result"
  author_name: "HATERS GONNA HATE"
  # Exlude TK with certain weapons from triggering the ban, adding "None" by default so it will exclude arty, tanks and road accidents
  # The weapon name should be as found in your game logs (case insensitive), know weapons at the time of writing: 'SMine M2 Kar98_Sniper M43 M1911 MK2_Grenade Satchel_M37 None P38 M24_Grenade M1A1 MP40 Kar98 STG44 Thompson MG42 Garand Tellermine43 Luger Satchel_3KG Panzershreck M1918A2_BAR M1919 G43 M1903 SMG_M3_GreaseGun M1_Carbine Bazooka'
  # To not exclude any weapons write exclude_weapons: [] 
  exclude_weapons: 
    - None
    - MK2_Grenade
    - M24_Grenade
  # TK after connect only counts as an offense for the first N minute after connecting, N is the number you set below
  max_time_after_connect_minutes: 5
  # A TK after connecting will be ignored if there's <N> kills before it
  ignore_tk_after_n_kills: 1
  # A TK after connecting will be ignored if there's <N> death before it
  ignore_tk_after_n_death: 2

  # If any of the conditions below are true the player won't be inspected upon TK
  whitelist_players:
    has_flag:
      - ✅
    is_vip: yes
    # Set to 0 for infinite
    has_at_least_n_sessions: 10
  # The maximum amount of TK tolerated after connecting, TK get counted if it wasn't excluded by any of the parameters above
  teamkill_tolerance_count: 1
  # If left unset, the webhook default to your audit log webhook
  discord_webhook_url: ""
  discord_webhook_message: "{player} banned for TK right after connecting"

LIVE_STATS:
  # A stats refresh is quite intensive on CPU, DISK and BANDWIDTH
  # smaller machines should choose at the very least 30 seconds, if not 60 to 120
  # The below is to compute live stats based on session (from the last connection) accross all games
  refresh_stats_seconds: 15
  # The below is to compute live stats for the current game and starts at the begining of the game, even if the 
  # player disconnect and reconnected multiple times, all his/her stats are counted
  refresh_current_game_stats_seconds: 5

# The below is not effective yet. 
# Here you can set your custom urls (if you have any)
# Make sure you set them in the same order as your server numbers
# Leave empty if you don't have any custom urls / domains, the default will be used
SERVER_URLS: []
# Example with custom urls:
# SERVER_URLS:
#   - http://server1.mydomain.com/
#   - http://server2.mydomain.com/
#   - http://server3.mydomain.com/

# The below is relevant only if your game server is hosted at GTX
# Filling those values will allow you to change your server name directly from the RCON
# The name change is visible in HLL after a map change, no need to restart the server
# You must fill you sftp information as well as credentials that have the right to access the sftp
# Don't forget to put your IP in quote, e.g: "42.42.42.42"
GTX:
  server_1:
    ip: "42.42.42.42"
    port: 42
    username: null
    password: null
  server_2:
    ip: null
    port: null
    username: null
    password: null
  server_3:
    ip: null
    port: null
    username: null
    password: null

# Set your custom text or transalation for each of the below keys. Logo urls and prefered stats and such
# If you have more that 3 server copy the whole SERVER_1 section 
SCOREBOT:
  SERVER_1:
    # Don't forget to replace with your IP:port or url, leave the /api/get_live_game_stats 
    STATS_URL: "https://<rcon IP or url>/api/get_live_game_stats"
    # Don't forget to replace with your IP:port or url, leave the /api/public_info
    INFO_URL: "https://<rcon IP or url>/api/public_info"
    # This is the public url
    SCOREBOARD_PUBLIC_URL: "https://stats1.hllfrance.org/"
    # The last slash matters
    SCORBOARD_BASE_PATH: "https://stats1.hllfrance.org/"
    # This is the public url
    PAST_GAMES_URL: "https://stats1.hllfrance.org/#/gamescoreboard"
    WEBHOOK_URL: "https://discord.com/api/webhooks/86....40/qlh....Ie3"
  
  SERVER_2:
    STATS_URL: "https://<rcon IP or url>/api/get_live_game_stats"
    INFO_URL: "https://<rcon IP or url>/api/public_info"
    # This is the public url
    SCOREBOARD_PUBLIC_URL: "https://stats2.hllfrance.org/"
    # The last slash matters
    SCORBOARD_BASE_PATH: "https://stats2.hllfrance.org/"
    # This is the public url
    PAST_GAMES_URL: "https://stats2.hllfrance.org/#/gamescoreboard"
    WEBHOOK_URL: "https://discord.com/api/webhooks/86....40/qlh....Ie3"

  SERVER_3:
    STATS_URL: "https://<rcon IP or url>/api/get_live_game_stats"
    INFO_URL: "https://<rcon IP or url>/api/public_info"
    # This is the public url
    SCOREBOARD_PUBLIC_URL: "https://stats2.hllfrance.org/"
    # The last slash matters
    SCORBOARD_BASE_PATH: "https://stats2.hllfrance.org/"
    # This is the public url
    PAST_GAMES_URL: "https://stats2.hllfrance.org/#/gamescoreboard"
    WEBHOOK_URL: "https://discord.com/api/webhooks/86....40/qlh....Ie3"


  COMMON:
    ALL_STATS_TEXT: "All stats on: "
    AUTHOR_NAME: "STATS LIVE HLL FRANCE - click here"
    AUTHOR_ICON_URL: "https://static.wixstatic.com/media/da3421_111b24ae66f64f73aa94efeb80b08f58~mv2.png/v1/fit/w_2500,h_1330,al_c/da3421_111b24ae66f64f73aa94efeb80b08f58~mv2.png"
    ELAPSED_TIME: "Game time: "
    # The number of top players to display from 1 to 100
    TOP_LIMIT: 10
    FOOTER_ICON_URL: "https://static.wixstatic.com/media/da3421_111b24ae66f64f73aa94efeb80b08f58~mv2.png/v1/fit/w_2500,h_1330,al_c/da3421_111b24ae66f64f73aa94efeb80b08f58~mv2.png"
    NO_STATS_AVAILABLE: "No stats recorded for that game yet"
    FIND_PAST_STATS: "Stats of past games on: "
    NEXT_MAP_TEXT: "Next map"
    VOTE: "vote(s)"
    PLAYERS: "players"
    ELAPSED_TIME: "Elasped game time: "

    # Discord markup is supported, you can add emoji too, TOP_KILLERS as an example of custom emoji. Do \<the emoji> on your discord to get that id
    TOP_KILLERS: "<:HLLBomb:868256234439073802> TOP KILLERS\n*kills* <:HLLBomb:868256234439073802>"
    TOP_RATIO: "TOP RATIO\n*kills/death*"
    TOP_PERFORMANCE: "TOP PERFORMANCE\n*kills/minute*"
    TRY_HARDERS: "TRY HARDERS\n*deaths/minute*"
    TOP_STAMINA: "TOP STAMINA\n*deaths*"
    TOP_KILL_STREAK: "TOP KILL STREAK\n*kill streak*"
    MOST_PATIENT: "MOST PATIENT\n*death by teamkill*"
    I_NEVER_GIVE_UP: "I NEVER GIVE UP\n*death streak*"
    I_M_CLUMSY: "YES I'M CLUMSY\n*teamkills*"
    I_NEED_GLASSES: "I NEED GLASSES\n*teamkill streak*"
    I_LOVE_VOTING: "I ❤ VOTING\n*num. votes started*"
    WHAT_IS_A_BREAK: "WHAT IS A BREAK?\n*ingame time*"
    SURVIVORS: "SURVIVORS\n*longest life (min.)*"
    U_R_STILL_A_MAN: "U'R STILL A MAN\n*shortest life (min.)*"

    # The stats items you an to display. I recommend you comment the line you don't want by adding a # at the beginning (before the -)
    STATS_TO_DISPLAY:
      - TOP_KILLERS
      - TOP_RATIO
      - TOP_PERFORMANCE
      - TRY_HARDERS
      - TOP_STAMINA
      - TOP_KILL_STREAK
      - I_NEVER_GIVE_UP
      - MOST_PATIENT
      - I_M_CLUMSY
      - I_NEED_GLASSES
      - I_LOVE_VOTING
      - WHAT_IS_A_BREAK
      - SURVIVORS
      - U_R_STILL_A_MAN
