---
- name: Installation des serveurs web
  hosts: SERVEUR-WEB
  remote_user: root

  tasks: 
    - name: Installation de Git
       apt: name=git state=latest

- name: Installation des serveurs bdd
  hosts: SERVEUR-BDD
  remote_user: root

  tasks: 
    - name: Installation de Mariadb
       apt: name=mariadb state=latest
...