---
- name: Installation des serveurs web
  hosts: SERVEUR-WEB
  remote_user: root
  roles:
    - nginx
  
- name: Installation des serveurs bdd
  hosts: SERVEUR-BDD
  remote_user: root
  roles:
    - mariadb
...